# fly.toml app configuration file generated for bustimes-org on 2024-06-06T00:12:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bustimes-org'
primary_region = 'lhr'
console_command = '/code/manage.py shell'

[build]

[deploy]

[env]
  PORT = '8000'
  ALLOWED_HOSTS = 'bustimes-org.fly.dev'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/staticfiles'
  url_prefix = '/static/'
